//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjektSemestralny.MVVM.Model
{
    using ProjektSemestralny.Core;
    using System;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;

    public partial class character : ObservableObject
    {
        private string character_name1;

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public character()
        {
            this.characters_equipment = new ObservableCollection<characters_equipment>();
        }

        public int character_id { get; set; }
        public string character_name 
        {
            get => character_name1;
            set
            {
                character_name1 = value;
                OnPropertyChanged();
            }
        }
        public Nullable<byte> character_level { get; set; }
        public Nullable<System.DateTime> creation_date { get; set; }
        public int player_id { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ObservableCollection<characters_equipment> characters_equipment { get; set; }
        public virtual player player { get; set; }
    }
}
