//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjektSemestralny.MVVM.Model
{
    using ProjektSemestralny.Core;
    using System;
    using System.Collections.Generic;

    public partial class characters_equipment : ObservableObject
    {
        private int? quantity1;

        public int character_id { get; set; }
        public int equipment_id { get; set; }
        public Nullable<int> quantity 
        { 
            get => quantity1;
            set 
            { 
                quantity1 = value;
                OnPropertyChanged();
            }
        }

        public virtual character character { get; set; }
        public virtual equipment equipment { get; set; }
    }
}
