//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjektSemestralny.MVVM.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PlayersDBEntities : DbContext
    {
        public PlayersDBEntities() : base("name=PlayersDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<character> characters { get; set; }
        public virtual DbSet<characters_equipment> characters_equipment { get; set; }
        public virtual DbSet<equipment> equipments { get; set; }
        public virtual DbSet<player> players { get; set; }
    }
}
